export type ApiError = {
	type: ErrorTypesEnum;
	message: ErrorMessagesEnum;
};

export enum ErrorTypesEnum {
	//Server
	SERVER_INTERNAL_ERROR = 'SERVER_INTERNAL_ERROR',
	VALIDATION_ERROR = 'VALIDATION_ERROR',

	// Auth
	AUTH_INVALID_EMAIL = 'AUTH_INVALID_EMAIL',
	AUTH_INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',
	AUTH_INVALID_ROLE = 'AUTH_INVALID_ROLE',
	USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
	USER_NON_EXISTENT = 'USER_NON_EXISTENT',
	AUTH_USER_NOT_ACTIVE = 'AUTH_USER_NOT_ACTIVE',

	// Listings
	LISTING_NOT_FOUND = 'LISTING_NOT_FOUND',
	LISTING_ALREADY_EXISTS = 'LISTING_ALREADY_EXISTS',
	LISTING_INVALID = 'LISTING_INVALID',
	LISTING_INVALID_TITLE = 'LISTING_INVALID_TITLE',
	LISTING_INVALID_DESCRIPTION = 'LISTING_INVALID_DESCRIPTION',
	LISTING_INVALID_START_DATE = 'LISTING_INVALID_START_DATE',
	LISTING_INVALID_END_DATE = 'LISTING_INVALID_END_DATE',
	LISTING_INVALID_HOURS_PER_DAY = 'LISTING_INVALID_HOURS_PER_DAY',
	LISTING_INVALID_JOB_DURATION_IN_DAYS = 'LISTING_INVALID_JOB_DURATION_IN_DAYS',
	LISTING_INVALID_JOB_OFFER_ID = 'LISTING_INVALID_JOB_OFFER_ID',
	LISTING_INVALID_EMPLOYER_ID = 'LISTING_INVALID_EMPLOYER_ID',
	LISTING_INVALID_LOCATION = 'LISTING_INVALID_LOCATION',
	LISTING_INVALID_PHOTO_URL = 'LISTING_INVALID_PHOTO_URL',
	NOT_ALLOWED_TO_CREATE_LISTING = 'NOT_ALLOWED_TO_CREATE_LISTING',

	LISTING_ID_NOT_PROVIDED = 'LISTING_ID_NOT_PROVIDED',

	//Applications
	ALREADY_APPLIED = 'ALREADY_APPLIED',

	//GENERAL
	NOT_FOUND = 'NOT_FOUND',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',
	BAD_REQUEST = 'BAD_REQUEST',
	ACCOUNT_NOT_ACTIVE = 'ACCOUNT_NOT_ACTIVE',

	//FILE
	FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR',
}

export enum ErrorMessagesEnum {
	//Server
	SERVER_INTERNAL_ERROR = 'Internal server error',
	VALIDATION_ERROR = 'Validation error',

	// Auth
	AUTH_INVALID_EMAIL = 'Invalid email',
	AUTH_INVALID_PASSWORD = 'Invalid password',
	AUTH_INVALID_ROLE = 'Invalid role',
	USER_ALREADY_EXISTS = 'User already exists',
	USER_NON_EXISTENT = 'User non existent',
	TOKEN_NOT_PROVIDED = 'Token not provided',
	INVALID_TOKEN = 'Invalid token',
	USER_VERIFICATION_NOT_FOUND = 'User verification not found',
	VERIFICATION_TOKEN_EXPIRED = 'Verification token expired',
	AUTH_USER_NOT_ACTIVE = 'User not active',

	// Listings
	LISTING_NOT_FOUND = 'Listing not found',
	LISTING_ALREADY_EXISTS = 'Listing already exists',
	LISTING_INVALID = 'Invalid listing',
	LISTING_INVALID_TITLE = 'Invalid title',
	LISTING_INVALID_DESCRIPTION = 'Invalid description',
	LISTING_INVALID_START_DATE = 'Invalid start date',
	LISTING_INVALID_END_DATE = 'Invalid end date',
	LISTING_INVALID_HOURS_PER_DAY = 'Invalid hours per day',
	LISTING_INVALID_JOB_DURATION_IN_DAYS = 'Invalid job duration in days',
	LISTING_INVALID_JOB_OFFER_ID = 'Invalid job offer id',
	LISTING_INVALID_EMPLOYER_ID = 'Invalid employer id',
	LISTING_INVALID_LOCATION = 'Invalid location',
	LISTING_INVALID_PHOTO_URL = 'Invalid photo url',
	NOT_ALLOWED_TO_CREATE_LISTING = 'Not allowed to create listing',

	//Employer
	EMPLOYER_NOT_FOUND = 'Employer not found',

	//GENERAL
	NOT_FOUND = 'Not found',
	UNAUTHORIZED = 'Unauthorized',

	//USER
	UPDATE_USER_NO_FIELDS = 'No fields to update',
	USER_NOT_FOUND = 'User not found',

	//FILES
	INVALID_FILE_TYPE = 'Invalid file type',
	FILE_SIZE_TOO_LARGE = 'File size too large',
	FILE_NOT_FOUND = 'File not found',
	FILE_EMPTY = 'File empty',
	FILE_UPLOAD_ERROR = 'File upload error',

	//GENERAL
	ACCOUNT_NOT_ACTIVE = 'Account not active',
}
